In [6]:
import numpy as np

a = np.array([1, 2, 3],dtype=np.int64)
b = np.array([[1, 2, 3],
             [4,5,6]],dtype=np.float64)

print("a:",a)
print("b:",b)
#print('a.dtype:',a.dtype)
# print('b.shape:',b.shape)
print('b.ndim:',b.ndim)
print('b.size:',b.size)

a: [1 2 3]
b: [[1. 2. 3.]
 [4. 5. 6.]]
b.ndim: 2
b.size: 6


In [ ]:
import numpy as np

a = np.array([1, 2, 3],dtype=np.int64)
b = np.array([[1, 2, 3],
             [4,5,6]],dtype=np.float64)


b_3X2 = b.reshape(3,2)
b_auto = b.reshape(-1,2) # -1 means "as many as needed"
print("b_3X2:",b_3X2)
print("b_auto:",b_auto) 


b_3X2: [[1. 2.]
 [3. 4.]
 [5. 6.]]
b_auto: [[1. 2.]
 [3. 4.]
 [5. 6.]]


In [ ]:
col1 = b[:,1]
print('col1 before:',col1)
col1[0] = 100 # slice is a view, not a copy
print('col1 after:',col1)
print('b after modifying col1:\n',b)


col1 before: [100.   5.]
col1 after: [100.   5.]
b after modifying col1:
 [[  1. 100.   3.]
 [  4.   5.   6.]]


In [11]:
c = b+10
print('c = b+10:\n',c)

c = b+10:
 [[ 11. 110.  13.]
 [ 14.  15.  16.]]


In [13]:
col2 = b[:,2].copy() # make a copy
print('col2 before:',col2)
col2[0] = 200 # does not affect b
print('col2 after:',col2)
print('b after modifying col2:\n',b)    


col1[0] = 1
d = b*2
print('d = b*2:\n',d)


col2 before: [3. 6.]
col2 after: [200.   6.]
b after modifying col2:
 [[  1. 100.   3.]
 [  4.   5.   6.]]
d = b*2:
 [[ 2.  2.  6.]
 [ 8. 10. 12.]]


练习 1（入门）
构造一个包含 1 到 6 的 2×3 整数数组 m（行优先），打印：
	1.	m.dtype 与 m.shape；
	2.	将 第二列 每个元素加 5 后输出整个数组；
	3.	用 reshape 把 m 变成 3×2 并输出形状。
提示：np.arange(1, 7).reshape(2, 3)；取第二列可用 m[:, 1]。
期望现象：类型为整型、形状正确；第二列元素各自增加 5；reshape 后形状变为 (3, 2)。

In [ ]:
import numpy as np  

m = np.arange(1,7).reshape(2,3) #make a range and reshape it to 2X3
print("m:",m)# print the matrix

print("m.dtype:",m.dtype) # print the data type of the matrix
print("m.shape:",m.shape) # print the shape of the matrix

col1 = m[:,1] # get the second column (index 1)
# remember this is a view, not a copy
col1 +=5 # add 5 to each element in col1
# this also changes m
print(m) # print m to see the change

m.reshape(3,2) # does not change m
print(m.reshape(3,2)) # print the reshaped matrix
print(m) # print m to see that it is unchanged
m = m.reshape(3,2) # reassign m to the reshaped matrix
print(m) # print m to see the change


m: [[1 2 3]
 [4 5 6]]
m.dtype: int64
m.shape: (2, 3)
[[ 1  7  3]
 [ 4 10  6]]
[[ 1  7]
 [ 3  4]
 [10  6]]


In [27]:
import numpy as np  

daily = [23.5, 25.1, 22.8, 24.0, 26.3, 27.1, 25.9]

daily_array = np.array(daily)# create a NumPy array from the list
print(daily_array)# print the array
print(daily_array.dtype) # print the data type
print(daily_array.shape) # print the shape
print(daily_array.ndim) # print the number of dimensions
print(daily_array.size) # print the number of elements

daily_array+= 0.5 # add 0.5 to each element

print(daily_array)# print the array after adding 0.5

daily_array1 = daily_array.reshape(-1,1) # make it a column vector
print(daily_array1) # print the reshaped array




[23.5 25.1 22.8 24.  26.3 27.1 25.9]
float64
(7,)
1
7
[24.  25.6 23.3 24.5 26.8 27.6 26.4]
[[24. ]
 [25.6]
 [23.3]
 [24.5]
 [26.8]
 [27.6]
 [26.4]]
